# (in wrangler.toml)
# Opt into backwards-incompatible changes through April 5, 2022.

# assert
# AsyncLocalStorage
# Buffer
# Crypto
# Diagnostics Channel
# EventEmitter
# path
# process
# Streams
# StringDecoder
# util
compatibility_flags = [ "nodejs_compat" ]